import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthContextProvider } from "@/app/actions/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OSEn jäsensivusto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fi">
      <body>
        <AuthContextProvider>
          <Navbar />
          <div className="p-4 min-h-screen w-screen bg-background">
            {children}
          </div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
