import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { isAdmin } from "@/app/actions";
import Navbar from "./components/Navbar";
import NavbarAdmin from "./components/NavbarAdmin";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OSEn jäsensivusto",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const admin = await isAdmin();

  if (admin) {
    return (
      <html lang="fi">
        <body className="lg:flex max-w-full box-border">
          <NavbarAdmin />
          <div className="grow lg:ml-72 max-lg:mt-16">{children}</div>
          <Toaster position="top-center" />
        </body>
      </html>
    );
  }

  return (
    <html lang="fi">
      <body className="lg:flex max-w-full box-border">
        <Navbar />
        <div className="grow lg:ml-72 max-lg:mt-16">{children}</div>
        <Toaster position="top-center" />
      </body>
    </html>
  );
};

export default RootLayout;
